quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: none

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Stream Processing Services API
          version: 0.0.1
          description: API for stream processing services
          contact:
            email: techsupport@redhat.com
            name: Stream Processing Services API Support
            url: https://github.com/strimzi/strimzi-kafka-sps-api
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html